module.exports = {
  products: [
    {
      _id: "111111111111111111111111",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 50,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 3.3,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 3.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 4,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 2,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
