export default {
  products: [
    {
      _id: "1",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 33,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "1",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "1",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "1",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "1",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "1",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
